[WIP] 感想を確認できる
company-library/company-library pull request #70
Opened 2022-12-29 05:13 UTC by katakoto291

2022-12-29 07:45 UTC, mongolyy requested changes

2022-12-29 07:45 UTC, mongolyy commented on src/components/bookDetails/impressionList.tsx
> +                      <span className="">{impression.user.name.substring(0, 1)}</span>
miroのデザインイメージだと表現されていなくて恐縮ですが、ユーザー名の先頭だけだと誰かがわからないので、
例えば、

- アイコンの隣にユーザー名を表示する列を追加する
- ホバーしたらツールチップっぽい感じで表示する

のように、ユーザーが特定できるように修正をお願いします 🙇

2023-01-14 10:14 UTC, katakoto291 commented on src/components/bookDetails/impressionList.tsx
> +                      <span className="">{impression.user.name.substring(0, 1)}</span>
ご確認ありがとうございます！
daisyuiを使ってツールチップで表示させるようにしてみました:pray:
https://daisyui.com/components/tooltip/#tooltip

![スクリーンショット 2023-01-14 19 12 37](https://user-images.githubusercontent.com/18738769/212466979-7a84ef55-6a04-464b-9ec1-5adb88308b7e.png)

2023-01-28 05:44 UTC, mongolyy approved these changes

2023-01-28 06:10 UTC, merged